### ISSUE TITLE
"Unknown item" warnings for tofu on startup

### ISSUE THREAD

**Issue by ladenedge** [SayWhatSayMon/VeganDelight#16]
When loading the current recipes, the game finds two "Unknown items."

- Unknown item 'vegandelight:cooked_smoked_tofu'
  - (Parsing error loading recipe vegandelight:cooked_smoked_tofu_slices_from_cutting)
- Unknown item 'vegandelight:cooked_tofu'
  - (Parsing error loading recipe vegandelight:cooked_tofu_slices_from_cutting)

```
[08:24:27] [Render thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe vegandelight:cooked_smoked_tofu_slices_from_cutting
com.google.gson.JsonSyntaxException: Unknown item 'vegandelight:cooked_smoked_tofu'
	at net.minecraft.world.item.crafting.ShapedRecipe.lambda$itemFromJson$2(ShapedRecipe.java:292) ~[forge-1.20.1-47.2.0_mapped_parchment_2023.09.03-1.20.1.jar:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {}
	at net.minecraft.world.item.crafting.ShapedRecipe.itemFromJson(ShapedRecipe.java:291) ~[forge-1.20.1-47.2.0_mapped_parchment_2023.09.03-1.20.1.jar:?] {re:classloading}
```

```
[08:24:27] [Render thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe vegandelight:cooked_tofu_slices_from_cutting
com.google.gson.JsonSyntaxException: Unknown item 'vegandelight:cooked_tofu'
	at net.minecraft.world.item.crafting.ShapedRecipe.lambda$itemFromJson$2(ShapedRecipe.java:292) ~[forge-1.20.1-47.2.0_mapped_parchment_2023.09.03-1.20.1.jar:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {}
	at net.minecraft.world.item.crafting.ShapedRecipe.itemFromJson(ShapedRecipe.java:291) ~[forge-1.20.1-47.2.0_mapped_parchment_2023.09.03-1.20.1.jar:?] {re:classloading}
```

It appears Cooked Tofu and Cooked Smoked Tofu are just missing. (Possibly on purpose?)

**Comment by SayWhatSayMon** [comment]
Adding items and rearranging Creative Tab as explained in PR. Additionally longer cooking times for tofu blocks will be added.

**Comment by SayWhatSayMon** [comment]
Done with PR.
